version: '3.8'

services:
  db:
    container_name: covid-benchmark-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - covid-network

  api:
    container_name: covid-benchmark-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - BASE_URL=${BASE_URL}
      - API_KEY=${API_KEY}
    depends_on:
      - db
    networks:
      - covid-network

  frontend:
    container_name: covid-benchmark-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:8080/api/v1
    depends_on:
      - api
    networks:
      - covid-network

networks:
  covid-network:
    driver: bridge

volumes:
  postgres_data:
    name: covid-benchmark-db-data