spring:
  application:
    name: Covid19 Benchmark
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

api:
  client:
    base-url: ${BASE_URL}
    api-key: ${API_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs.html